"""
Django settings for DrinkingWine project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import firebase_admin
from firebase_admin import credentials

CONFIG = {
    "type": "service_account",
    "project_id": "reactdjango-17278",
    "private_key_id": "19b79e9f6ad4b4e5eef0652ddc28c8ae1d6e9727",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDI4OrIbUDd31cw\n7NjVIZ6JpyL3jkCZACWPmLhqDA3Lif5alJF2pbz3zFb//aH88Hrx38T0kfMosTHY\nWbmHqnAla7aeDHFC/Nf+Kr0WrMWGwPx5J/dxVQvpBaumSYDdDELge+ziXviDrs/f\nFE64HNxsTK7iZQzztoskjhybRF4TZjA8HSRsNX9DlToWiE5ED+rJdkjhYhuIXP7c\ns94oLXl0DfSynyP2aejq+zzvbpaZbArMYSmRFOWLjVG1JhdFjoZe63omcEAsn+lO\n07fFVji8IupfwY+77ekmznau/x0LF+cbMI+soSv8Q0VJ1HqeJWQ4r0wUB+b5wotS\nL/OpmIhVAgMBAAECggEACNkUqQIG8BQ8/EQHw6YuHCoRzuL5KBlq43RP9dEqGmOt\nocJsKym0X8XPCd+GGboN8EbG9MQo+GCLAtiQ5M+LuQTm5PdEqzVaiNt2ZgqeI11a\nFuFnyMTSOCVZINiZUHiQdDWBLZy5SDOUUbh3RIIg7gmX+mjbtTBpLecEjjeTXTn4\nYFj2Kq//ykf91xHPBXFjgPiPkbuOcSquWbj7oTEd7SPxfSI8N+sCdE5LFdWF+Irw\nCJhAoJUVHOOHxSUmxPJkxtjFW+6b5+IpP+Ic3EIBGy40BvkiYtUflO9FaxDWpFEd\nRR2hjztiBJbbWH0Qxktyx65wbG1bgkEN6inWO/udgQKBgQDwcL14fuctylYnKVo7\n7Utkv1t0d3BmYtrtNGBGUaeUbRuVd3eks5cow7d86Qz2VO6zlaQCsbqjx9E8c+4u\n+FYI7bAxxXijMT5OOeMPxXSb00ZK1DaAJU9GlPVWa30VdvLlIpytZ/7peTceobO/\nCBP706X5o+7intTQYs/glrhj3QKBgQDV4MaO3rAfm8sQpRTvwnPL8wqVEVaOD8UJ\n0Uxg5dQh9aKtpm1Ch1r+pbhkuohPNHIsr+oYQRuOGBq9Gjvvcl1ZB/mFNmblXPyG\nNSjBr1bKcnEXOQYIfyHovixl8GsOkifw+4NULfcqv0ZVTaJV1YuyI2uxQKRQqFQ7\nxeS1vEZK2QKBgBOs9iRNJjfeDezIeoTa50eITUCboYwPXOD6X0KB3hfMUeyKSTUm\nKSGB2psTKydhTeNORIyf5KkQafPrfLtFQS0b3kZEZZndJr8aB5W7z84MnPz0nr0f\n0HvzJpx60VKXWEsd6Ppbv0V10OflzaK9U31RFYz3OE49NycSXvZ+/vnVAoGACG0g\npYRUgApNR8yZNJD+quxaYGEcfeBVLPvX/IFRiDz7Ocgyyco3ZYz15NIMiMJSNTyB\nBo+aHFEKzKR59AcXcmiEBiGMkEDHmioB/w9/Zd54YifW+wK3PUowyZtdPGe5tx7R\nn8Fn2YFLrhSu7p7JMC2BEqyvTJY1K12ykw5l3pECgYEA3XI+caCg2b7ConAOGqxU\nABnnsyYt2CzIAhdZzRhv8t4RdbpwNPynG9Xk8vvdMFy+HbXD8+d+5f/DfbEY4POB\nn+5UKE7UkIxQhndyRh39BolkvOwNQ+NnD3kzwWS6Yl/my74gKkeLsrNmOVJvp7k7\nZc1LpPOxrabw9ZOA6brvABI=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-3j2o0@reactdjango-17278.iam.gserviceaccount.com",
    "client_id": "103712469206557480775",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-3j2o0%40reactdjango-17278.iam.gserviceaccount.com"
}
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "C:/Users/alexa/credentials.json"
cred = credentials.Certificate(CONFIG)
firebase_admin.initialize_app(cred)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 0

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7zz_$3q(0lqb*(3^+*8u+5fxz$oel5z37--n1t%^u4riyo0$45'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = ['http://localhost:3000',]

ROOT_URLCONF = 'DrinkingWine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'client', 'build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DrinkingWine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'client', 'build', 'static')]
